Repository cert-manager/approver-policy, pull requests merged in 2022-05, with the labels that each got.

#55 Go 1.18 and updates go modules
  Makefile
  go.mod
  go.sum
  pkg/apis/policy/v1alpha1/register.go
  pkg/apis/policy/v1alpha1/types_certificaterequestpolicy.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/approver/allowed/evaluator.go
  pkg/approver/allowed/evaluator_test.go
  pkg/approver/constraints/evaluator.go
  pkg/approver/constraints/evaluator_test.go
  pkg/approver/constraints/validation.go
  pkg/approver/constraints/validation_test.go
  pkg/approver/evaluator.go
  pkg/approver/fake/evaluator.go
  pkg/approver/manager/fake/fake.go
  pkg/approver/manager/manager.go
  pkg/approver/manager/predicate/predicate.go
  pkg/approver/manager/predicate/predicate_test.go
  pkg/approver/manager/review.go
  pkg/approver/manager/review_test.go
  pkg/internal/cmd/cmd.go
  pkg/internal/controllers/certificaterequests.go
  pkg/internal/controllers/certificaterequests_test.go
  pkg/internal/controllers/test/rbac.go
  pkg/internal/controllers/test/review.go
  pkg/internal/controllers/test/selector.go
  pkg/internal/controllers/test/util.go
  pkg/internal/webhook/tls/tls.go
  test/env/env.go
  test/smoke/tests.go
Labels: dco-signoff: yes, approved, lgtm, size/XXL

#57 Updates Dockerfile go version to v1.18
  Dockerfile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#60 fix hello.world example policy, commonName must be an object
  README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#63 Update logo to use small version with correct size
  README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm
