Repository cert-manager/approver-policy, pull requests merged in 2022-12, with the labels that each got.

#166 Fix flakey tests and improve the test log output
  pkg/internal/controllers/test/util.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#167 Update distroless base image
  Dockerfile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#170 Add explicit namespaces to all namespaced resources in Helm charts
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/templates/metrics-service.yaml
  deploy/charts/approver-policy/templates/metrics-servicemonitor.yaml
  deploy/charts/approver-policy/templates/role.yaml
  deploy/charts/approver-policy/templates/rolebinding.yaml
  deploy/charts/approver-policy/templates/serviceaccount.yaml
  deploy/charts/approver-policy/templates/webhook.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#168 Bugfix Invalid Deployment Yaml When Specifying Resources
  deploy/charts/approver-policy/templates/deployment.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#176 Add Tim to OWNERS file
  OWNERS
Labels: dco-signoff: yes, approved, size/XS, lgtm
