Repository cert-manager/approver-policy, pull requests merged in 2023-01, with the labels that each got.

#183 Allow webhook TLS secret to be created by controller
  deploy/charts/approver-policy/templates/role.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#184 Upgrade go dependencies
  go.mod
  go.sum
  pkg/internal/approver/allowed/evaluator_test.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#189 Remove leader election in integration tests
  .gitignore
  Makefile
  pkg/internal/controllers/test/util.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#190 BUGFIX & Run goroutine using manager
  pkg/internal/controllers/certificaterequestpolicies.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#188 Add hostNetwork and scheduling options
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/crds/policy.cert-manager.io_certificaterequestpolicies.yaml
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, ok-to-test

#177 Allow custom labels to be added to resources
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/_helpers.tpl
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test
