Repository cert-manager/approver-policy, pull requests merged in 2023-02, with the labels that each got.

#200 Upgrade dependencies
  .github/workflows/release.yaml
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: dco-signoff: yes, approved, size/L, lgtm

#201 Improve makefile
  .github/workflows/release.yaml
  .gitignore
  Makefile
  deploy/charts/approver-policy/Chart.yaml
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/crds/policy.cert-manager.io_certificaterequestpolicies.yaml
  deploy/charts/approver-policy/templates/deployment.yaml
  docs/api/api.md
  hack/ci/create-cluster.sh
  hack/ci/delete-cluster.sh
  hack/ci/run-smoke-test.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/update-codegen.sh
  hack/update-helm-docs.sh
  hack/util/verify.sh
  hack/verify-helm-docs.sh
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/approver/manager/predicate/predicate_test.go
  pkg/internal/approver/manager/review.go
  pkg/internal/approver/manager/review_test.go
  pkg/internal/controllers/test/controllers_test.go
  pkg/internal/webhook/tls/tls.go
Labels: dco-signoff: yes, approved, lgtm, size/XXL

#202 Fixes a typo
  docs/examples/all-options.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm
