Repository cert-manager/approver-policy, pull requests merged in 2023-11, with the labels that each got.

#298 Use cert-manager's servertls.CertificateSource and simplify webhook code
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.yaml
  pkg/internal/cmd/cmd.go
  pkg/internal/cmd/options/options.go
  pkg/internal/webhook/tls/tls.go
  pkg/internal/webhook/webhook.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#302 fix: typos in error message wrapping
  pkg/internal/controllers/certificaterequestpolicies.go
  pkg/internal/controllers/certificaterequestpolicies_test.go
  pkg/internal/controllers/certificaterequests.go
  pkg/internal/controllers/certificaterequests_test.go
  pkg/internal/controllers/ssa_client/certificaterequestpolicy_status.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#303 fix: should not change existing condition of type
  pkg/internal/controllers/certificaterequests.go
  pkg/internal/controllers/certificaterequests_test.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#305 fix: dynamic cert runnable must NOT be leader election aware
  pkg/internal/cmd/cmd.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#277 feat: add allowed CEL validation rules
  .gitattributes
  Makefile
  deploy/charts/approver-policy/templates/crds/policy.cert-manager.io_certificaterequestpolicies.yaml
  docs/api/api.md
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/tools.go
  osvars.mk
  pkg/apis/policy/v1alpha1/types_certificaterequestpolicy.go
  pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/approver/allowed/allowed.go
  pkg/internal/approver/allowed/evaluator.go
  pkg/internal/approver/allowed/evaluator_test.go
  pkg/internal/approver/allowed/validation.go
  pkg/internal/approver/allowed/validation_test.go
  pkg/internal/approver/constraints/constraints.go
  pkg/internal/approver/constraints/evaluator_test.go
  pkg/internal/approver/constraints/validation_test.go
  pkg/internal/approver/validation/cache.go
  pkg/internal/approver/validation/cache_test.go
  pkg/internal/approver/validation/certificaterequest.pb.go
  pkg/internal/approver/validation/certificaterequest.proto
  pkg/internal/approver/validation/validator.go
  pkg/internal/approver/validation/validator_test.go
Labels: dco-signoff: yes, approved, lgtm, size/XL

#256 CEL expressions approver design
  design/20230726-cel-policy.md
  design/template.md
Labels: dco-signoff: yes, approved, lgtm, size/XL, ok-to-test

#308 Add missing copyright
  pkg/internal/approver/validation/cache.go
  pkg/internal/approver/validation/cache_test.go
  pkg/internal/approver/validation/validator.go
  pkg/internal/approver/validation/validator_test.go
  pkg/internal/metrics/metrics.go
  pkg/internal/metrics/metrics_test.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#309 Don't use ROOTDIR environment variable in tests.
  Makefile
  pkg/internal/approver/manager/predicate/predicate_test.go
  pkg/internal/approver/manager/review_test.go
  pkg/internal/controllers/test/controllers_test.go
  test/env/util.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#311 chore(deps): upgrade github.com/google/cel-go
  go.mod
  go.sum
  pkg/internal/approver/allowed/validation_test.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#310 docs: brush-up policy examples
  docs/examples/all-options.yaml
  docs/examples/default-deny-all.yaml
  docs/examples/deny-all.yaml
  docs/examples/example.com.yaml
  docs/examples/plugin.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm
