Repository cert-manager/approver-policy, pull requests merged in 2023-09, with the labels that each got.

#263 Fix uninitialized controller-runtime logger
  .gitignore
  pkg/internal/cmd/cmd.go
  pkg/internal/controllers/test/util.go
Labels: dco-signoff: yes, approved, lgtm, size/S

#266 Upgrade to cert-manager 1.13.0
  go.mod
  go.sum
  pkg/internal/cmd/cmd.go
  pkg/internal/controllers/test/util.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#265 Enable grouping for dependabot
  .github/dependabot.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#264 HELM: add options for configuring image
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/_helpers.tpl
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#272 Refactor Evaluate preparing for CEL
  pkg/internal/approver/allowed/evaluator.go
Labels: dco-signoff: yes, approved, size/L, lgtm
