Repository cert-manager/approver-policy, pull requests merged in 2024-03, with the labels that each got.

#388 Allow replicaCount to be set to int or string
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#390 Document the nameOverride Helm chart value and add it to the JSON schema
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/values.linter.exceptions
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#396 Allow Deployment strategy customization when installing the Helm chart
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#398 Fix vulnerability GO-2024-2611 (CVE-2024-24786) by upgrading to google.golang.org/protobuf@v1.33.0
  go.mod
  go.sum
Labels: dco-signoff: yes, approved, size/XS, lgtm

#403 Allow users to configure the priorityClassName field in the Helm chart
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/NOTES.txt
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#404 Run govulncheck daily to alert us to vulnerabilities in the main branch
  .github/workflows/govulncheck.yaml
  README.md
  klone.yaml
  make/_shared/go/01_mod.mk
  make/_shared/go/README.md
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/L, lgtm

#407 Fix typo
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#409 Helm: add http_proxy, https_proxy, and no_proxy
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#413 Fix linters
  .golangci.yaml
  pkg/internal/approver/allowed/allowed.go
  pkg/internal/approver/allowed/evaluator_test.go
  pkg/internal/approver/allowed/validation_test.go
  pkg/internal/approver/constraints/constraints.go
  pkg/internal/approver/constraints/evaluator.go
  pkg/internal/approver/constraints/evaluator_test.go
  pkg/internal/approver/constraints/validation_test.go
  pkg/internal/approver/manager/predicate/predicate_test.go
  pkg/internal/approver/manager/review_test.go
  pkg/internal/cmd/options/options.go
  pkg/internal/controllers/certificaterequestpolicies.go
  pkg/internal/controllers/certificaterequestpolicies_test.go
  pkg/internal/controllers/certificaterequests.go
  pkg/internal/controllers/certificaterequests_test.go
  pkg/internal/controllers/test/rbac.go
  pkg/internal/controllers/test/review.go
  pkg/internal/controllers/test/selector.go
  pkg/internal/controllers/test/util.go
  pkg/internal/webhook/validator_test.go
  pkg/internal/webhook/webhook.go
  test/env/env.go
  test/smoke/tests.go
Labels: dco-signoff: yes, approved, lgtm, size/XL
