Repository cert-manager/approver-policy, pull requests merged in 2024-01, with the labels that each got.

#333 Remove deprecated make targets
  make/02_mod.mk
Labels: dco-signoff: yes, approved, size/XS, lgtm

#336 Remove unnecessary types
  pkg/internal/controllers/test/rbac.go
  pkg/internal/controllers/test/ready.go
  pkg/internal/controllers/test/review.go
  pkg/internal/controllers/test/selector.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#334 Upload junit and coverage results to ARTIFACTS folder
  make/test-smoke.mk
  make/test-unit.mk
  pkg/internal/controllers/test/controllers_test.go
  test/env/env.go
  test/smoke/smoke_test.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#343 Add allow-all example
  docs/examples/allow-all.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#346 Upgrade repository-base module
  .github/workflows/make-self-upgrade.yaml
  Makefile
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/repository-base/base/Makefile
Labels: dco-signoff: yes, approved, size/XS, lgtm

#354 Upgrade oci module
  klone.yaml
  make/00_mod.mk
  make/_shared/oci-image/01_mod.mk
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#353 fix: should reconcile certificate request policies consistently
  pkg/internal/controllers/certificaterequestpolicies.go
  pkg/internal/controllers/certificaterequestpolicies_test.go
  pkg/internal/controllers/ssa_client/certificaterequestpolicy_status.go
  pkg/internal/controllers/test/review.go
Labels: dco-signoff: yes, approved, size/L, lgtm, ok-to-test

#358 Use standardised release process
  make/02_mod.mk
Labels: dco-signoff: yes, approved, size/XS, lgtm

#359 Docs: updating values.yaml for better comment docs
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm, needs-ok-to-test

#361 Cleanup Chart.yaml and README.md
  deploy/charts/approver-policy/Chart.yaml
  deploy/charts/approver-policy/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm
