Repository cert-manager/approver-policy, pull requests merged in 2024-06, with the labels that each got.

#453 chore(deps): bump github.com/cert-manager/cert-manager to v1.15.0
  go.mod
  go.sum
  pkg/internal/cmd/cmd.go
Labels: dco-signoff: yes, approved, size/L, lgtm

#456 Add support for JSON logging format
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
  pkg/internal/cmd/options/options.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#462 add webhook cert configs
  pkg/internal/cmd/cmd.go
  pkg/internal/cmd/options/options.go
Labels: dco-signoff: yes, approved, lgtm, size/S, ok-to-test
