Repository cert-manager/approver-policy, pull requests merged in 2024-02, with the labels that each got.

#367 Remove README header since it is already included in the artifacthub sidebar
  deploy/charts/approver-policy/README.md
Labels: dco-signoff: yes, approved, size/XS, lgtm

#371 docs(api): fenced code block to fix generated API docs
  deploy/charts/approver-policy/templates/crd-policy.cert-manager.io_certificaterequestpolicies.yaml
  docs/api/api.md
  pkg/apis/policy/v1alpha1/types_certificaterequestpolicy.go
Labels: dco-signoff: yes, approved, size/M, lgtm

#376 Add 'crds.enabled' and 'crds.keep' options to generated CRDs
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/crd-policy.cert-manager.io_certificaterequestpolicies.yaml
  deploy/charts/approver-policy/values.yaml
  klone.yaml
  make/00_mod.mk
  make/_shared/helm/crd.template.footer.yaml
  make/_shared/helm/crd.template.header.yaml
  make/_shared/helm/crds.mk
  make/_shared/helm/helm.mk
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#340 Enable helm-tool linter and schema generator
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/values.linter.exceptions
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
  make/00_mod.mk
Labels: dco-signoff: yes, approved, size/L, lgtm

#381 Use same include statement for labels everywhere
  deploy/charts/approver-policy/templates/clusterrole.yaml
  deploy/charts/approver-policy/templates/clusterrolebinding.yaml
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/templates/metrics-service.yaml
  deploy/charts/approver-policy/templates/metrics-servicemonitor.yaml
  deploy/charts/approver-policy/templates/role.yaml
  deploy/charts/approver-policy/templates/rolebinding.yaml
  deploy/charts/approver-policy/templates/serviceaccount.yaml
  deploy/charts/approver-policy/templates/webhook.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#383 Add optional PodDisruptionBudget to the Helm chart
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/NOTES.txt
  deploy/charts/approver-policy/templates/_helpers.tpl
  deploy/charts/approver-policy/templates/poddisruptionbudget.yaml
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm

#384 Set a size limit on the emptyDir used for /tmp
  deploy/charts/approver-policy/templates/deployment.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#385 Platform engineer can now set Topology Spread Constraints using a Helm chart value
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, lgtm, size/S

#386 Remove emptydir /tmp volume because it is unused
  deploy/charts/approver-policy/templates/deployment.yaml
Labels: dco-signoff: yes, approved, size/XS, lgtm

#387 Make all Deployment related Helm values global
  deploy/charts/approver-policy/README.md
  deploy/charts/approver-policy/templates/NOTES.txt
  deploy/charts/approver-policy/templates/deployment.yaml
  deploy/charts/approver-policy/values.linter.exceptions
  deploy/charts/approver-policy/values.schema.json
  deploy/charts/approver-policy/values.yaml
Labels: dco-signoff: yes, approved, size/L, lgtm
