Repository cert-manager/approver-policy, pull requests merged in 2024-12, with the labels that each got.

#539 Remove unused Makefile variables
  make/00_mod.mk
Labels: dco-signoff: yes, approved, size/XS, lgtm

#548 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/kind/00_kind_image_versions.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#553 [CI] Self-upgrade merging self-upgrade-main into main
  klone.yaml
  make/_shared/kind/00_kind_image_versions.mk
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, approved, size/M, lgtm

#543 Add Helm chart OCI release to GH automation
  .github/workflows/release.yaml
  RELEASE.md
  klone.yaml
  make/00_mod.mk
  make/02_mod.mk
  make/_shared/helm/crds.mk
  make/_shared/helm/helm.mk
Labels: dco-signoff: yes, approved, size/L, lgtm

#554 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/make-self-upgrade.yaml
  klone.yaml
  make/_shared/oci-build/00_mod.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm

#555 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
Labels: dco-signoff: yes, approved, size/M, lgtm
