Repository cert-manager/approver-policy, pull requests merged in 2025-01, with the labels that each got.

#571 Add support for client-gen
  pkg/apis/policy/v1alpha1/types_certificaterequestpolicy.go
Labels: dco-signoff: yes, approved, size/XS, lgtm, ok-to-test

#572 Fix private key algorithm constraint always erroring when set
  pkg/internal/approver/constraints/evaluator.go
  pkg/internal/approver/constraints/evaluator_test.go
Labels: dco-signoff: yes, approved, lgtm, size/S, ok-to-test

#573 [CI] Self-upgrade merging self-upgrade-main into main
  .github/workflows/govulncheck.yaml
  .github/workflows/make-self-upgrade.yaml
  deploy/crds/crds/policy.cert-manager.io_certificaterequestpolicies.yaml
  klone.yaml
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/helm/crds.mk
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
Labels: dco-signoff: yes, approved, lgtm, size/XXL

#551 Simplify integration test setup
  make/test-unit.mk
  pkg/internal/approver/manager/predicate/predicate_test.go
  pkg/internal/approver/manager/review_test.go
  pkg/internal/controllers/test/controllers_test.go
  test/env/certmanager.go
  test/env/crd.go
  test/env/env.go
Labels: dco-signoff: yes, approved, size/L, lgtm
